ControleDeLista/Models/ErrorViewModel.cs
namespace ControleDeLista.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleDeLista/Controllers/HomeController.cs
using ControleDeLista.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControleDeLista.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleDeLista/Controllers/ListaController.cs
using Microsoft.AspNetCore.Mvc;

namespace ControleDeLista.Controllers
{
    public class ListaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ControleDeLista/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <p>Sistema de controle de preços para atacado ou varejo</p>
</div>

ControleDeLista/Views/Lista/Index.cshtml
@{
    ViewData["Title"] = "Produtos";
}

<h1 class="diplay-4">Listagem de Produtos</h1>
<style>
    .table{
    background-color: goldenrod;
    }
    .btn{
    color: black;
    text-decoration:underline;
    font-size: 15px
    }
</style>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Produto</th>
      <th scope="col">Valor Varejo</th>
      <th scope="col">Valor Atacado</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Chocolate Snickers</td>
      <td>R$3,00</td>
      <td>R$2,50</td>
      <td>
        <div class="btn-group" role="group">
            <a role="button" class="btn btn-primary">Editar</a>
            <a role="button" class="btn btn-danger">Apagar</a>
        </div>
       </td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Chocolate Bis Xtra Original</td>
      <td>R$4,00</td>
      <td>R$3,30</td>
      <td>
        <div class="btn-group" role="group">
            <a role="button" class="btn btn-primary">Editar</a>
            <a role="button" class="btn btn-danger">Apagar</a>
        </div>
       </td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Chocolate Kit-Kat</td>
      <td>R$4,00</td>
      <td>R$2,87</td>
      <td>
        <div class="btn-group" role="group">
            <a role="button" class="btn btn-primary">Editar</a>
            <a role="button" class="btn btn-danger">Apagar</a>
        </div>
       </td>
    </tr>
  </tbody>
</table>

ControleDeLista/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Minha Lista</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleDeLista.styles.css" asp-append-version="true" />
    <style>
        body{
        background-color: lightgoldenrodyellow;
        }

        .head-1 {
        background-color:red;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Minha Lista</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lista" asp-action="Index">Lista</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle De Produtos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>